// <auto-generated />
namespace RoadTrip_4.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class abilityToDeleteRoadTrip : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(abilityToDeleteRoadTrip));
        
        string IMigrationMetadata.Id
        {
            get { return "201312271323429_abilityToDeleteRoadTrip"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
